# LLM Critic agent settings
vlm:
  # model: "qwen/qwen3-vl-30b-a3b-instruct"     # Image Input Model
  model: "google/gemini-3.6-flash"              # Video Input Model
  # model: "google/gemini-3.1-pro-preview"      # Video Input Model
  base_url: "https://openrouter.ai/api/v1"
  temperature: 0.3        # keep it low for critical evaluation, but not zero to avoid deterministic behavior
  max_output_tokens: 1000  # limit output length
  timeout_seconds: 90        # video clips are short so dont need too long
  frequency_penalty: 0.2    # Occassionally the vlm would repeat the same things over and over so this is to limit that

  # video recording settings
  as_images: true      # whether to slice the video into frames and pass them to the VLMFeedbackAgent (true : false)
  video_length: 200     # length of the video clip to record for evaluation (in steps, default is 200)
  sample_rate: 8        # sample rate for video recording (frames per second)
  frame_cap: 1000       # maximum number of frames to process (to avoid excessive memory usage)    
  camera_angle: 0       # 0: default (isometric facing right), 1: opposite (isometric facing left), 2: front, 3: top down view  

  logging:
    jsonl_enabled: true
