# LLM parameters
# model: gpt-4-0314  # LLM model (other options are gpt-4, gpt-4-0613, gpt-3.5-turbo-16k-0613)

# Eureka parameters
iteration: 2 # how many iterations of Eureka to run
sample: 4 # number of Eureka samples to generate per iteration
num_eval: 5 # number of evaluation episodes to run for the final reward


# Eureka Agent settings:
agent:
  model: "x-ai/grok-code-fast-1"
  base_url: "https://openrouter.ai/api/v1"

